### ISSUE TITLE
Liskov Principle

### ISSUE THREAD

**Issue by jaimepizarr** [AddstarMC/Pandora#30]
**AngryPigmen**
https://github.com/AddstarMC/Pandora/blob/752dc7496c9a2548a47384b99f3031b6002966be/src/au/com/addstar/pandora/modules/AngryPigmen.java#L19

We can see there's probably a violation of the Liskov Principle in this class, because the methods onEnable, onDisable and setPandoraInstance haven't been implemented. This means that objects from Module type can't be substituted by this class due to the lack of the implementation of these behaviours.

You could delete the implementation of the Module interface because the AngryPigmen doesn't implement the interface methods, and only leave the Listener implementation.

**ItemGiving**
https://github.com/AddstarMC/Pandora/blob/master/src/au/com/addstar/pandora/modules/ItemGiving.java 
We can see here's also a probably violation of this principle. It's the same from the case above. But also the onTabComplete method is not implemented, so it's probably wrongly implemented.  

**(Recomendation made for educational purposes)**

**Comment by Narimm** [comment]
I recommend you get your money back from where ever you got taught..

**Comment by Narimm** [comment]
I am also recommending that you get a **D** on whatever CS course you were posting this to get credit for...
You clearly don't understand what you're commenting on - either you didn't read the project properly OR more likely you just don't get it.
