### ISSUE TITLE
Dependency Inversion Principle

### ISSUE THREAD

**Issue by AlvaradoEddo** [AddstarMC/Pandora#31]
**Class ItemGiving**
https://github.com/AddstarMC/Pandora/blob/master/src/au/com/addstar/pandora/modules/ItemGiving.java 
Dentro de tu método setPandoraIntance estas colocando como parámetro con un tipo de bajo nivel, lo que genera una dependecia a esa clase, cerrándolo a posibles extensiones, podrías hacer que tu método reciba un objeto de tipo JavaPlugin para solucionarlo.

(Recomendación realizada por fines académicos)

**Comment by Narimm** [comment]
I am also recommending that you get a D on whatever CS course you were posting this to get credit for...
You clearly don't understand what you're commenting on - either you didn't read the project properly OR more likely you just don't get it.

Either way ...get a course refund
